### ISSUE TITLE
"Building Scalable Applications with Erlang" cancelled?

### ISSUE THREAD

**Issue by aurora** [sger/ElixirBooks#6]
I've pre-ordered this book at Amazon in August and it's still not available for shipping. I searched the Website of the Publisher and can't find any information regarding this book. I tried to contact the publisher a while ago, but did not get any feedback ... 

I wonder if this title got cancelled and should in this case be removed from the list?

**Comment by sger** [comment]
Hello,
Try also contact the author of this book.Some extra info http://www.mypearsonstore.com/bookstore/building-scalable-applications-with-erlang-9780321636461 from the website "It is currently scheduled to be available on Feb 5, 2025. ".Well now its 2016 nine years to write a book....

**Comment by aurora** [comment]
Oh well, that's really a long time ahead ... (o_o) ... unfortunately i am unable to dig anything up regarding the author, either. But i am also not involved in the erlang/elixir community. Still somehow new to this all ...

**Comment by aurora** [comment]
Just wanted to let you know that i got an update from Amazon regarding this. Estimated delivery-date is Dec 9, 2017(!). So apparently it wasn't cancelled but delayed.

**Comment by fearofcode** [comment]
Time passes...
